nelmio_api_doc:
    documentation:
        info:
            title: MTG Viewer
            description: Une simple application pour visualiser les cartes Magic The Gathering
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
