env:
    browser: true
    es2021: true
extends:
    - airbnb-base
    - plugin:vue/vue3-essential
    - '@vue/eslint-config-airbnb'
parserOptions:
    ecmaVersion: latest
    sourceType: module
rules:
    import/no-extraneous-dependencies:
        - error
        - devDependencies: false
    indent:
        - error
        - 4
    vue/html-indent:
        - error
        - 4
    max-len:
        - off # Off - use vue/max-len instead
    import/prefer-default-export:
        - off
    no-else-return:
        - error
    vue/max-len:
        - error
        -   code: 250
            tabWidth: 4
            ignoreHTMLAttributeValues: true
